name: DeployWatch Test Deployment

on:
  workflow_dispatch: # Allows you to trigger this workflow manually from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Deployment
        uses: peter-evans/create-deployment@v4
        with:
          environment: production
          transient_environment: false
          auto_inactive: true

      - name: Set deployment status to success
        uses: peter-evans/create-deployment-status@v4
        with:
          environment: production
          state: success