   name: Test Actions

   on:
     workflow_dispatch:

   jobs:
     test:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Test create-deployment
           uses: peter-evans/create-deployment@v4
           with:
             environment: production
